version: "2"
services:
  web:
    image: nginx:1.15.2-alpine
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./src:/wp
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp
    networks:
      - wp-network
  wp:
    build: ./
    volumes:
      - ./src:/wp
    depends_on:
      - db
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - wp-network
  db:
    image: mysql:5.7.17
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - wp-network
networks:
    wp-network:
        driver: bridge